[build]
  command = "env HUGO_BASEURL = 'https://www.damonqin.tech/' npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "env HUGO_BASEURL = 'https://www.damonqin.tech/' npm run build-preview"
