languageCode = "en-us"
title = "Hi, I'm Damon Qin!"
baseurl = "/"
theme = "aerial"

[params]
  name = "Damon Qin"
  about = """
  <span>I LIKE ELEGANT CODE</span>
  <span>&nbsp;&bull;&nbsp;</span>
  <span>I ENJOY BEAUTIFUL DESIGN</span>
  <span>&nbsp;&bull;&nbsp;</span>
  <span>I'M WRITING PROGRAMS</span>
  """
  copyright = "2017 Damon Qin"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = "asdf"
  favicon = "favicon.ico"
  custom_css = ["css/fix-theme.css"]



[[menu.main]]
  name = "Blog<sup>[beta]</sup>"
  url = "https://blog.damonqin.tech/"
  weight = 1

[[menu.main]]
  name = "About Me"
  url = "https://resume.damonqin.tech"
  weight = 2



[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/DamonQin"

[[params.social]]
  medium = "Gitlab"
  icon = "gitlab"
  link = "https://gitlab.com/DamonQin"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/damonqin/"

[[params.social]]
  medium = "500px"
  icon = "500px"
  link = "https://500px.com/damonqin"

[[params.social]]
  medium = "Weibo"
  icon = "weibo"
  link = "http://weibo.com/aeonchinx"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:received@icloud.com"
